# @format

version: '3.9'

services:
  # test-app:
  #   image: golang:1.19
  #   container_name: "Todos"
  #   build: .
  #   ports:
  #     - 8080:8080
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app
  #   command:
  #     - "app"
  db:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - ~/Users/macbook/Documents/my-project/redis-master/redis-with-config/config/redis.conf:/usr/local/etc/redis/redis.conf
      # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
